export default [
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "lt40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "lt40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "5- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "lt40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "70 79",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "70 79",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "70 79",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "5- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "20 29",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "5- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "70 79",
    menopause: "ge40",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "70 79",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "9 11",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "9 11",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "right_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "5- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "45 49",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "45 49",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "lt40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "1 -17",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "35 39",
    invnodes: "1 -17",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "lt40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "1 -17",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "6 8",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "1 -14",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "right_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "10 14",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "central",
    irradiat: "yes",
  },
  {
    Class: "no recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "no recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "0- ",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "central",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "right_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "1 -17",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "45 49",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "right_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "50 54",
    invnodes: "9 11",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "1 -17",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "6 8",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "1 -14",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "9 11",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "9 11",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "right_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "35 39",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "40 44",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "50 54",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "right_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "1 -14",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "right_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "9 11",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "2 -26",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "right_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "right",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "15 19",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "yes",
    degmalig: 2,
    breast: "right",
    breastquad: "right_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "yes",
    degmalig: 2,
    breast: "left",
    breastquad: "central",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "9 11",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "25 29",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "right_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "10 14",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "premeno",
    tumorsize: "35 39",
    invnodes: "1 -17",
    nodecaps: "yes",
    degmalig: 3,
    breast: "right",
    breastquad: "right_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "40 44",
    invnodes: "6 8",
    nodecaps: "yes",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "30 34",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 2,
    breast: "left",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "30 39",
    menopause: "premeno",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_up",
    irradiat: "yes",
  },
  {
    Class: "recurrence events",
    age: "60 69",
    menopause: "ge40",
    tumorsize: "20 24",
    invnodes: "0 2",
    nodecaps: "no",
    degmalig: 1,
    breast: "right",
    breastquad: "left_up",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "40 49",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
  {
    Class: "recurrence events",
    age: "50 59",
    menopause: "ge40",
    tumorsize: "30 34",
    invnodes: "3 5",
    nodecaps: "no",
    degmalig: 3,
    breast: "left",
    breastquad: "left_low",
    irradiat: "no",
  },
];
